# -*- coding: utf-8 -*-
"""Cópia de Prática_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N-pgYKs4RDuJNZQYBbYT1jJveHqHjtW-

## Fundamentos

**1 -** Escreva um código para exibir uma mensagem "Olá Mundo"
"""

print("Hello WORLD")

"""**2 -** Escreva duas varíaveis e exiba elas com um print

"""

var1= "ALO"
var2= "TODO MUNDO"

print(var1)
print(var2)

"""**3 -** Escreva abaixo um programa completo que leia dois números (devem ser digitados pelo usuário) e calcule e exiba a média. Quando executado, o programa deve gerar a seguinte saída: <br>`Entre com o primeiro número: 10`<br>`Entre com o segundo número: 5`<br>`Média: 7.5`<br>**Dica**: No Python3 o retorno fa função `input('mensagem')` é uma `String`, que deve ser convertida para `float()` para uso em cálculos."""

n1= float(input('Entre com o primeiro numero:'))
n2= float(input('Entre com o segundo numero: '))

media = (n1+n2)/2

print(media)

"""**4 -** Crie uma lista de frutas com 5 frutas e exiba as frutas na tela"""

lista_frutas = ['banana','maça','aabacate','amora','kiwi']
print (lista_frutas)

"""**5 -** Faça um for para percorrer a lista de frutas criadas (não é preciso criar de novo) e print em tela o nome de cada uma das frutas"""

for lista in lista_frutas:
  print (lista_frutas)

"""**6 -** Faça um for em de 1 até 10 e imprima os números pares na tela"""

numeros = [1,2,3,4,5,6,7,8,9,10]
for i in range (len(numeros)):
    if numeros[i] % 2 == 0:
      print(numeros[i])

"""**7 -** Defina uma lista com 20 números diferentes.Escreva um código para contar a frequência de um número em uma lista de números"""

import random
numeros = [random.randint(0,10) for i in range(20)]

x = int(input((print("Digite um número"))))
j = 0
print(numeros)
for numero in numeros:
 if (numero == x):
   j = j+1
print(j)

"""**8 -** Crie um dicionário para armazenar o objetvo Pokemon - Pikachu, contendo as propriedades tipo (Choque), ataque (15), defesa (15) e HP (15)"""

pokemon = {
    "tipo": "Choque",
    "ataque": 15,
    "defesa": 15,
    "hp": 15
}

print(pokemon)

"""**9 -** Calcule o IV deste Pokemon obedecendo a seguinte regra: O IV é dado pela soma do ataque, defesa e do HP. Caso seja 45 a resposta é 100, caso seja entre 38 e 43, 90. Entre 35 e 38 - 80, entre 30 e 35 - 70 e menor que 30, 50."""

#IV = pokemon['ataque'] + pokemon['defesa'] + pokemon['hp']
IV = pokemon.get('ataque') + pokemon.get('hp') + pokemon.get('defesa')
resposta = 0

if (IV == 45):
  resposta = 100
elif (IV >= 38 and IV <= 44):
  resposta = 90
elif (IV >= 35 and IV < 38):
  resposta = 80
elif (IV >= 30 and IV < 35):
  resposta = 70
elif (IV < 30):
  resposta = 50

print(resposta)

"""**10 -** Dado a lista de [0,1,2,3,4] escreva um codigo que irá imprimir o valor da soma dessa lista?"""

lista_soma = [0,1,2,3,4]

soma = sum(lista_soma)

print(soma)

"""**11 -** Crie uma lista vazia e implemente um código que verifique se está lista está vazia (deverá retornar True) """

lista_vazia = []

if len(lista_vazia) == 0:
    print("Lista vazia")
else:
    print("Lista cheia")

"""**12 -** Escreva um código que irá receber um nome digitado por um usuário e irá retornar o número de caracteres neste nome"""

nome = input(print("Digite um nome:"))
print(len(nome))

"""**13 -** Escreva um código para encontrar quais números são divisíveis por 7 e múltiplos de 5 entre 1500 e 2700 (ambos incluídos)"""

for num in range(1500,2701):
  if ((num % 7 == 0) and (num % 5 != 0)):
    print(num)

"""**14 -** Escreva um programa para calcular a mediana de 3 números digitados pelo usuário (Não vale usar função pronta)"""

num1 = int(input("Digite o 1º número"))
num2 = int(input("Digite o 2º número"))
num3 = int(input(print("Digite o 3º número")))
lista = [num1,num2,num3]
lista.sort()
print(lista[1])

"""**15 -** Bônus Crie uma lista, embaralhe esta lista e imprima a versão embaralhada. Dica: Procurar por importação da função shuffle. No Bloco de texto abaixo escreva o que encontrou sobre a função e o que entendeu sobre importação."""

lista = [1,2,3,4,5]
random.shuffle(lista)
print(lista)

"""/* Escreva aqui a resposta em texto comentada */"""