# -*- coding: utf-8 -*-
"""Cópia de Exercícios_Colab_26082020.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O9lysJiboThdH_yCEPWH65wHz-gh8J-l

**LISTA DE EXERCÍCIOS**
"""



from google.colab import drive
drive.mount('/content/drive')

"""EXERCÍCIO 1 - FAÇA UM SCRIPT VERIFIQUE SE UM NÚMERO (*num*) É PAR OU IMPAR:"""

import random
num = random.randint(1, 100)

print(num)

if (num%2==0):
  print("PAR")
else:
  print ("IMPAR")

"""EXERCÍCIO 2 - FAÇA UMA SCRIPT QUE CALCULA UMA EXPRESSÃO MATEMÁTICA DADO 2 INTEIROS (*num1, num2 e op*) E UM OPERADOR (String = '+', '-', '*', '/'):"""

import random
num1 = random.randint(0, 100)
num2 = random.randint(0, 100)
op = ['+', '-', '*', '/'][random.randint(0, 3)]

print(num1, num2, op)

if op == '+':
  print (num1 + num2)

if op == '-':
  print (num1-num2)

if op == '*':
  print (num1*num2)

if op == '/':
  print (num1/num2)

"""EXERCÍCIO 3 - FAÇA UM SCRIPT QUE IDENTIFIQUE SE UM NÚMERO INTEIRO (*num*) É PRIMO OU NÃO"""

import random
num = random.randint(1, 100)

if num%2==1:
    print("primo")
else:
    print("não primo")

"""EXERCÍCIO 4 - FAÇA UM SCRIPT QUER RETORNE DE UMA LISTA DE INTEIROS (*lista*):

*   MAIOR ELEMENTO
*   MENOR ELEMENTO
*   TAMANHO

**DESAFIO:** NÃO USE FUNÇÕES *min(), max() e len()*!
"""

import random

lista = [random.randint(0,10) for i in range(5)]

print(lista)

maior = 0
inicializado = False
tamanho = 0

for elemento in lista:
  if not inicializado:
    inicializado = True
    menor = elemento
  if (elemento <= menor):
    menor = elemento
  elif (elemento >= maior):
    maior = elemento
  tamanho = tamanho + 1

print("O tamanho é:", tamanho)
print("O maior é:", maior)
print("O menor é:", menor)

"""EXERCÍCIO 5 - FAÇA UM SCRIPT QUE RETORNE DE UMA LISTA DE INTEIROS (*lista*):

* A MEDIA
* A MEDIANA
* A MODA
"""

import random

lista = [random.randint(0,10) for i in range(5)]

print(lista)

lista = ([random.randint(0,10) for i in range(5)])
n0=int(lista[0])
n1=int(lista[1])
n2=int(lista[2])
n3=int(lista[3])
n4=int(lista[4])
listaN=n0,n1,n2,n3,n4

print(listaN)

media=n0+n1+n2+n3+n4/len(listaN)
print(media)

mediana=(sorted(listaN))
print(mediana[2])

"""EXERCÍCIO 6 - FAÇA UMA FUNÇÃO QUE TENHA COMO ENTRADA UMA LISTA DE INTEIROS (*idades*) E RETORNE UMA LISTA COM AS FAIXAS DE CADA IDADE, DE ACORDO COM AS REGRAS A SEGUIR:<br>
* '<18', 
* '18 A 21', 
* '21 A 27', 
* '28 A 35', 
* '36 A 50', 
* '50 A 65', 
* '65+'
"""

import random

idades = [random.randint(5, 95) for i in range(100)]

print(idades)

# SEU CODIGO AQUI ...

dicionario = {
    '<18': {
        'min': 5,
        'max': 17
    },
    '18 A 21': {
        'min': 18,
        'max': 20
    },
    '21 A 27': {
        'min': 21,
        'max': 27
    },
    '28 A 35': {
        'min': 28,
        'max': 35
    },
    '36 A 50': {
        'min': 36,
        'max': 49
    },
    '50 A 65': {
        'min': 50,
        'max': 64
    },
    '65+': {
        'min': 65,
        'max': 95
    },
}

def faixas_de_idades(idades):
  lista_retorno = []
  for idade in idades:
    for i in dicionario:
      if idade >= dicionario[i]['min'] and idade <= dicionario[i]['max']:
        lista_retorno.append(i)
  return lista_retorno

print(faixas_de_idades(idades))

"""EXERCÍCIO 7 - DADA UM LISTA (*cabecalho*) CONTENDO O CABEÇALHO DE UMA TABELA, FAÇA AS SEGUINTES TRANSFORMAÇÕES:<br>
* Remova espaços a direita e a esquerda (função \<string\>.strip())
* Deixe todas a letras maiúsculas (função \<string\>.upper())
* substitua " " (espaços) por "_" (função \<string\>.replace())
"""

import random

lista = [random.randint(1, 10) for i in range(20)]

print(lista)

numero = int(input("Digite um número de 1 a 10: "))

contador = 0
if numero not in lista:
  print("Número não existe na lista")
else:
  for i in lista:
    if numero == i:
      contador += 1
  print(f"O número aparece {contador} vezes.")